from flask import *
from flask import Flask, render_template, Response
import os
from werkzeug.utils import secure_filename
import label_image
import cv2
import time

def load_image(image):
    text = label_image.main(image)
    return text

app = Flask(__name__)

@app.route('/')
@app.route('/first')
def first():
    return render_template('first.html')

 
  
    
@app.route('/login')
def login():
    return render_template('login.html')
@app.route('/chart')
def chart():
    return render_template('chart.html')


@app.route('/index')
def index():
    return render_template('index.html')

@app.route('/capture_photo', methods=['POST'])
def capture_photo():
    # Open the webcam
        cap = cv2.VideoCapture(0)

    # Allow the camera to warm up (2 seconds delay)
        time.sleep(2)

    # Capture a frame from the webcam
        ret, frame = cap.read()

    # Save the captured frame as "output.png"
        cv2.imwrite('output.png', frame)

        # Release the webcam
        cap.release()

        result = load_image('output.png')
        result = result.title()
        d = {
        "Asthma Plant":" → Euphorbia hirta is a pantropical weed, originating from the tropical regions of the Americas. It is a hairy herb that grows in open grasslands, roadsides and pathways. It is widely used in traditional herbal medicine across many cultures, particularly for asthma, skin ailments, and hypertension. Often recognized for its potential respiratory benefits, considered generally safe for various ages and genders, but pregnant individuals should exercise caution and seek medical advice before use. Its usage typically involves preparing extracts for respiratory support, yet professional guidance is advisable for proper oral consumption or medicinal purposes.",
        'Avaram':" → Senna auriculata is a leguminous tree in the subfamily Caesalpinioideae. It is commonly known by its local names matura tea tree, avaram or ranawara, or the English version avaram senna. It is the State flower of Telangana. It occurs in the dry regions of India and Sri Lanka. Generally safe for all ages and genders, it is traditionally used to address conditions like diabetes and skin disorders. However, caution and consultation with healthcare providers are recommended, especially for young children and during pregnancy. The mode of use typically involves consuming it as a tea or infusion, with proper dosage guided by healthcare professionals. ",
        "Balloon Vine":" → Cardiospermum halicacabum, known as the lesser balloon vine, balloon plant or love in a puff, is a climbing plant widely distributed across tropical and subtropical areas of Africa, Australia, and North America that is often found as a weed along roads and rivers.Generally safe for various age groups and both genders, it has been traditionally used for skin conditions, allergies, and as a mild diuretic. Caution and healthcare consultation are advised, particularly for specific age groups and during pregnancy. Dosage recommendations should be followed under healthcare professional guidance, and the plant's various parts may be used in forms like decoctions or topical applications, adhering to traditional practices and healthcare advice.",
        "Bellyache Bush":" → Jatropha gossypiifolia, commonly known as bellyache bush, black physicnut or cotton-leaf physicnut, is a species of flowering plant in the spurge family, Euphorbiaceae. The species is native to Mexico, Philippines, South America, Gujarat State, and the Caribbean islands. Traditionally used for digestive issues, skin conditions, and as an anti-inflammatory agent, it is generally considered safe for various age groups and genders, with caution and healthcare consultation recommended. Limited research exists on its use during pregnancy, and proper dosage, whether in decoctions, infusions, or topical applications, should be determined under the guidance of healthcare professionals and traditional practices.",
        "Benghal Dayflower":" → Commelina benghalensis, commonly known as the Benghal dayflower, tropical spiderwort, or wandering Jew, kanshira in Bengali, is a perennial herb native to tropical Asia and Africa. Traditionally used for its diuretic properties and in the treatment of inflammatory conditions, it is generally considered safe for various age groups and both genders, with caution and healthcare consultation recommended. Limited research exists on its use during pregnancy, and proper dosage, whether in infusions or topical applications, should be determined under the guidance of healthcare professionals and traditional practices.",
        "Big Caltrops":" → A caltrop also known as caltrap, galtrop, cheval trap, galthrap, galtrap, calthrop, jackrock or crow's foot is an area denial weapon made up of two or more sharp nails or spines arranged in such a manner that one of them always points upward from a stable base for example, a tetrahedron. Historically, caltrops were part of defences that served to slow the advance of troops, especially horses, chariots, and war elephants, and were particularly effective against the soft feet of camels. In modern times, caltrops are effective when used against wheeled vehicles with pneumatic tires. Typically, it's consumed as a supplement, yet guidance from experts is recommended for appropriate dosages and usage.",
        "Black Honey Shrub":" → (Phyllanthus reticulatus) Black-Honey Shrub is usually a much-branched somewhat climbing shrub, rarely a small tree. Leaves are ovate-oblong to elliptic, 1-5 cm long, 0.7-3 cm wide, produced on short lateral branchlets, looking like leaflets of a compound leaf. The plant has medicinal uses, treating conditions like malaria and diabetes. It also has practical applications; stems are used for hut construction, twigs as toothbrushes, and fruits, roots, and stems yield black ink and dye. Ripe fruits are consumed during famine and sold in markets. Propagation is done through seeds. The Black-honey shrub serves diverse purposes in traditional medicine, daily life, and local economies.",
        "Bristly Wild Grape":" → Cyphostemma setosum - Bristly Wild Grape is a succulent climber clothed with bristly hairs. Leaves are trifoliate rarely lower ones simple, fleshy, nearly stalkless, shortly stalked, elliptic, ovoate to obovate, blunt, rounded at the base, stringly sawtoothed, up to 7 x 5 cms. Often acknowledged for its potential benefits related to joint health and bone support, considered generally safe for various ages and genders. However, pregnant individuals should approach its usage with caution and seek medical advice before use. It's typically utilized by preparing extracts for joint-related issues, yet professional guidance is recommended for oral consumption or medicinal purposes. ",
        "Butterfly Pea":" → Clitoria ternatea, commonly known as Asian pigeonwings, bluebellvine, blue pea, butterfly pea, cordofan pea or Darwin pea is a plant species belonging to the family Fabaceae, endemic and native to the Indonesian island of Ternate. In India, it is revered as a holy flower, used in daily puja rituals. Pregnant individuals should exercise caution and seek advice from healthcare professionals regarding its use. Understanding recommended daily doses and modes of consumption is paramount, with guidance from healthcare practitioners or herbalists ensuring safe and effective utilization.",
        'Cape Gooseberry':" → Physalis peruviana, is a South American plant native to Colombia, Ecuador and Peru in the nightshade family, commonly known as Cape gooseberry or goldenberry. Rich in vitamins and antioxidants, it contributes to overall health, although it's not specifically associated with curing diseases. Generally safe for all ages, its consumption is versatile and can be enjoyed fresh, in salads, desserts, or jams. There are no strict daily doses, but moderation is recommended. Cape Gooseberry is commonly consumed by both men and women, and while it is generally considered safe during pregnancy, individual reactions may vary, necessitating consultation with healthcare professionals for personalized advice.",
        "Common Wireweed":" → Sida acuta, the common wireweed, is a species of flowering plant in the mallow family, Malvaceae. It is believed to have originated in Central America, but today has a pantropical distribution and is considered a weed in some areas. It is recognized in traditional medicine for its potential diuretic and anti-inflammatory properties. Generally safe for various age groups and both genders, caution is advised for pregnant individuals. Common Wireweed can be used in different forms, such as teas or infusions, with adherence to recommended guidelines ensuring safe and effective utilization.",
        "Country Mallow":" → Sida cordifolia is a perennial subshrub of the mallow family Malvaceae native to India. It has naturalized throughout the world, and is considered an invasive weed in Africa, Australia, the southern United States, Hawaiian Islands, New Guinea, and French Polynesia. Is esteemed for its traditional medicinal uses, encompassing anti-inflammatory and anti-asthmatic properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals.",
        "Crown Flower":" → Calotropis gigantea, the crown flower, is a species of Calotropis native to Cambodia, Vietnam, Bangladesh, Indonesia, Malaysia, Thailand, Sri Lanka, India, China, Pakistan, and Nepal. It is a large shrub growing to 4 m tall. It has clusters of waxy flowers that are either white or lavender in colour. Traditional medicinal uses is boasting anti-inflammatory and anti-fungal properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage depends on the intended use, with guidance from healthcare practitioners. ",
        "Green Chireta":" → Andrographis paniculata, commonly known as creat or green chiretta, is an annual herbaceous plant in the family Acanthaceae, native to India and Sri Lanka. It is widely cultivated in Southern and Southeastern Asia, where it has been believed to be a treatment for bacterial infections and some diseases. Particularly used for immune-boosting and anti-inflammatory properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, necessitating consultation with healthcare professionals. Dosage depends on the intended use.",
        "Holy Basil":" → Ocimum tenuiflorum, commonly known as holy basil, tulsi or tulasi, is an aromatic perennial plant in the family Lamiaceae. It is native to the Indian subcontinent and widespread as a cultivated plant throughout the Southeast Asian tropics. Its potential medicinal properties, includes anti-inflammatory and antioxidant effects. It's used traditionally for respiratory conditions, stress, and digestive issues. Generally considered safe for all ages. It is generally used by both men and women. Dosage may vary based on the form of use (tea, supplement, etc.).Holy Basil can be consumed as tea, in culinary dishes, or taken as supplements. It's also used topically.",
        "Indian Copperleaf":" → Acalypha indica is an herbaceous annual that has catkin-like inflorescences with cup-shaped involucres surrounding the minute flowers. It is mainly known for its root being attractive to domestic cats, and for its various medicinal uses. It occurs throughout the Tropics. Traditional medicinal applications are anti-inflammatory and antifungal properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage may vary depending on the intended use, and guidance from healthcare practitioners.",
        "Indian Jujube":" → Ziziphus mauritiana, also known as Indian jujube, Indian plum, Chinese date, Chinese apple, ber, and dunks is a tropical fruit tree species belonging to the family Rhamnaceae. It is prized for its nutritional richness and potential health benefits. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage may vary based on the intended use, and guidance from healthcare practitioners. Indian Jujube is a versatile ingredient in various culinary dishes, with adherence to recommended guidelines ensuring safe and effective utilization.  ",
        'Indian Sarsaparilla':" → Hemidesmus indicus, Indian sarsaparilla is a species of plant found in South Asia. It occurs over the greater part of India, from the upper Gangetic plain eastwards to Assam and in some places in central, western and South India. The root is a substitute for sarsaparilla. Is esteemed for its traditional medicinal uses, encompassing anti-inflammatory and antioxidant properties. Generally safe for various age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage may vary based on the intended use, with guidance from healthcare practitioners or herbalists recommended. Often consumed as a herbal decoction.",
        "Indian Stinging Nettle":" → Tragia involucrata, the Indian stinging nettle, is a species of plant in the family Euphorbiaceae. It's known for treating conditions like arthritis, allergies, and skin ailments due to its anti-inflammatory and antihistaminic properties. This plant, while widely considered safe for most ages and genders, requires caution during pregnancy due to limited research on its effects. Consulting healthcare professionals is advisable before usage, especially for pregnant women or individuals with specific health concerns. Doses for daily use may vary, often consumed as teas, extracts, or in topical forms for skin conditions.",
        "Indian Thornapple":" → Datura innoxia, known as pricklyburr, recurved thorn-apple, downy thorn-apple, Indian-apple, lovache, moonflower, nacazcul, toloatzin, toloaxihuitl, tolguache or toloache, is a species of flowering plant in the family Solanaceae. is a flowering plant native to India and Southeast Asia. Recognized for its trumpet-shaped flowers and spiky fruits, it contains toxic tropane alkaloids. While historically used in traditional medicine for its potential psychoactive properties, its toxicity makes it risky and not recommended for such purposes. There are no safe age groups, and use is generally discouraged for all individuals. The toxic effects apply universally, regardless of gender. No safe dosage exists, emphasizing the plant's inherent risks. ",
        "Indian Wormwood":" → Scientifically known as Artemisia Indica. Indian Wormwood is found in India and East Asia. It is found in the Himalayas at altitudes of 300-2400 m. Flowering: August-October. Medicinal uses: An infusion of leaves is used in the treatment of nervous and spasmodic affections, in asthma and in diseases of the brain. Recognized for its aromatic, silvery-green leaves, it has been traditionally used in medicine for its potential anti-inflammatory and antimicrobial properties. Caution is advised, as some Artemisia species, including A.absinthium, may have toxic components. Generally considered safe, caution is advised for pregnant individuals, and consulting healthcare professionals is recommended for specific use during pregnancy. Dosage may vary based on the intended application, and guidance from herbalists or healthcare practitioners is advisable.",
        "Ivy Gourd":" → Scientifically known as Coccinia grandis. Ivy gourd is a plant. The leaves, root, and fruit are used to make medicine. Ivy gourd is most often used for diabetes. People also use ivy gourd for gonorrhea, constipation, wounds, and other conditions, but there is no good scientific evidence to support these uses. Recognized for its small, cucumber-like fruits, it is a popular ingredient in Asian cuisine, featured in dishes like stir-fries and curries. Besides its culinary uses, ivy gourd is known for potential health benefits, including traditional medicinal applications such as managing diabetes.Generally safe for consumption across age groups and genders, pregnant individuals should consult healthcare professionals for personalized advice.",
        "Kokilaksha":" → Scientifically known as Asteracantha longifolia. The plant is an Ayurvedic herb used to make medicines for several gastrointestinal, kidney, reproductive, liver, and bone disorders. Kokilaksha is native to India and also to other places like Srilanka, Malaysia, Nepal and Myanmar. Kokilaksha means having eyes like Kokila the Indian cuckoo. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. Dosages for daily use may vary based on the intended purpose and formulation, often administered as decoctions, powders, or in traditional formulations. No specific age or gender restrictions are typically outlined due to its traditional usage.",
        "Land Caltrops":" → Tribulus terrestris is an annual plant in the caltrop family widely distributed around the world. It is adapted to thrive in dry climate locations in which few other plants can survive. It is native to warm temperate and tropical regions in southern Eurasia and Africa. Recognized for its spiky fruits, it has traditional uses in herbal medicine, particularly for male reproductive health. Additionally, it's popular in fitness communities as a supplement.  Caution is advised, and consulting with a healthcare professional is recommended before using it for medicinal or supplemental purposes. Generally considered safe for various age groups, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. ",
        "Madagascar Periwinkle":" → Catharanthus roseus, commonly known as bright eyes, Cape periwinkle, graveyard plant, Madagascar periwinkle, old maid, pink periwinkle, rose periwinkle, is a species of flowering plant in the family Apocynaceae. It is native and endemic to Madagascar, but grown elsewhere as an ornamental and medicinal plant. This vibrant and low-maintenance flowering plant is recognized for its attractive blooms and medicinal properties. The plant produces glossy, dark green leaves and flowers with shades of pink, red, or white. Madagascar periwinkle contains alkaloids that have been used in traditional medicine, and it's a source of compounds used in the production of certain chemotherapy drugs for treating cancer. Despite its beauty, the plant is toxic and should be handled with care.",
        'Madras Pea Pumpkin':" → Scientifically known as Cucumis maderaspatanus. Madras pea pumpkin is a perennial herb, climbing or trailing up to 3 m, stem bristly-hairy. Tendrils are simple, thread-like. Leaves are arrow shaped, hastate, ...  Often associated with managing blood sugar levels and aiding digestion. Considered generally safe for various age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. As for age restrictions, it's suitable for consumption across different age brackets when used as a food source. However, specific medicinal doses and usage might require guidance, especially for pregnant women or individuals with health conditions.",
        "Malabar Catmint":" → Anisomeles indica, or catmint, is a species of herbaceous plant native to eastern Asia and naturalized on some Pacific islands. The plant is valued for its potential medicinal properties, including anti-inflammatory and antibacterial effects. It thrives in warm climates, is low-maintenance, and can be grown in pots or in well-drained soil.",
        "Mexican Mint":" → Coleus amboinicus, synonym Plectranthus amboinicus, is a semi-succulent perennial plant in the family Lamiaceae with a pungent oregano-like flavor and odor. Its ability to improve the health of your skin, detoxify the body, defend against colds, ease the pain of arthritis, relieve stress and anxiety, treat certain kinds of cancer, and optimize digestion. Generally considered safe for various age groups, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage varies based on the intended use.",
        "Mexican Prickly Poppy":" → Argemone mexicana is a species of poppy found in Mexico and now widely naturalized in many parts of the world. An extremely hardy pioneer plant, it is tolerant of drought and poor soil, often being the only cover on new road cuttings or verges. It has bright yellow latex. It has a history of traditional medicinal uses, including addressing skin conditions, respiratory issues, and serving as a mild sedative. However, caution is essential as the plant contains alkaloids that can be toxic, particularly in its seeds. Medicinal use, especially internal consumption, should be approached with care, and consultation with healthcare professionals is advised.",
        "Mountain Knotgrass":" → Aerva lanata, the mountain knotgrass, is a woody, prostrate or succulent, perennial herb in the family Amaranthaceae, native to Asia, Africa. It has been included as occurring in Australia by the US government, but it is not recognised as occurring in Australia by any Australian state herbarium. Various parts of the plant have been employed in treating conditions such as kidney stones, urinary disorders, and as a diuretic in traditional medicine. With potential anti-inflammatory and antimicrobial properties, caution is advised, and consultation with healthcare professionals is recommended, especially for pregnant individuals.",
        "Nalta Jute":" → Scientifically known as Corchorus olitorius. Jute mallow or nalta jute is a species of shrub in the family Malvaceae. Together with C. capsularis it is the primary source of jute fiber. The leaves and young fruits are used as a vegetable, the dried leaves are used for tea and as a soup thickener, and the seeds are edible.  While not primarily recognized for extensive medicinal applications, some traditional practices attribute mild therapeutic benefits. It is commonly used in various culinary dishes, contributing a unique flavor profile. Generally considered safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy.",
        "Night Blooming Cereus":" → Scientifically as Selenicereus grandiflorus. Regardless of genus or species, night-blooming cereus flowers are almost always white or very pale shades of other colors, often large, and frequently fragrant. Most of the flowers open after nightfall, and by dawn, most are in the process of wilting. Benefits such as aiding in insomnia and relieving certain mild digestive discomforts, though scientific evidence supporting these claims remains limited. Typically considered safe for diverse age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy.",
        "Panicled Foldwing":" → Dicliptera paniculata - Panicled Foldwing. Panicled Foldwing is an erect herb, 0.6-1.2 m tall. Young shoots are usually 4-sided; adult shoots 6-sided, white spreading bristle-hairy. Ovate leaves opposite, equal and unequal; leaf-stalk 3-5 mm. Benefits such as aiding in digestive discomfort or minor skin conditions, although scientific evidence supporting these claims is limited or anecdotal. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to the lack of comprehensive research on its effects during pregnancy.",
        "Prickly Chaff Flower":" → Achyranthes aspera is a species of plant in the family Amaranthaceae. It is distributed throughout the tropical world. It can be found in many places growing as an introduced species and a common weed. It is an invasive species in some areas, including many Pacific Islands environments. It's attributed with properties such as anti-inflammatory, antimicrobial, and antipyretic (fever-reducing) characteristics, often used to address conditions like wounds, skin ailments, fever, and digestive discomfort. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Punarnava":" → Boerhaavia diffusa is a species of flowering plant in the four o'clock family which is commonly known as punarnava, red spiderling, spreading hogweed, or tarvine. It is taken in herbal medicine for pain relief and other uses. The leaves of Boerhaavia diffusa are often used as a green vegetable in many parts of India. Renowned for its diuretic properties, it's often used to support kidney and urinary health. Additionally, Punarnava is attributed with anti-inflammatory, hepatoprotective (liver-protective), and antioxidant characteristics. Generally regarded as safe for various age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy.",
        'Purple Fruited Pea Eggplant':" → Scientifically as Solanum trilobatum. It is a very good brain stimulant. It removes chest, nose and head congestion. It relieves dyspepsia impairment of digestion. In traditional medicine, it's commonly used to address respiratory issues like coughs, colds, and asthma, as well as for skin conditions and digestive discomfort. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Purple Tephrosia":" → Tephrosia purpurea is a species of flowering plant in the family Fabaceae, that has a pantropical distribution. It is a common wasteland weed. In many parts it is under cultivation as green manure crop. It is found throughout India and Sri Lanka in poor soils. Common names include: Bengali. It's attributed with various therapeutic effects, including anti-inflammatory, antioxidant, and antimicrobial properties. In traditional practices, it's often used to address conditions such as digestive issues, skin ailments, and inflammatory conditions. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Rosary Pea":" → Abrus precatorius, commonly known as jequirity bean or rosary pea, is a herbaceous flowering plant in the bean family Fabaceae. It is a slender, perennial climber with long, pinnate-leafleted leaves that twines around trees, shrubs, and hedges.  While its seeds are visually appealing, they contain a toxic compound called abrin, making them highly poisonous if ingested. Due to this toxicity, it's crucial to handle the seeds with extreme caution and prevent accidental ingestion, as even a small amount can be lethal. Despite its toxic nature, the plant has been historically used in some traditional practices for its purported medicinal properties, including potential applications in treating various ailments. ",
        "Shaggy Button Weed":" → Scientifically known as Diodia virginiana, is a small flowering plant found in various regions. While not prominently recognized for medicinal use, some traditional practices attribute mild potential benefits, often citing its usage for minor ailments or as a mild diuretic. Typically considered safe for diverse age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Small Water Clover":" → Scientifically known as Marsilea minuta. Water clovers are fast growers, with vestita and quadrifolia ranging between 4 inches and one foot of maximum height, depending on water depth ... Often using it for minor ailments or as part of traditional remedies. Generally considered safe for diverse age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy.",
        "Spiderwisp":" → It is known by many common names including Shona cabbage, African cabbage, spiderwisp, cat's whiskers, chinsaga and stinkweed. It is an annual wildflower native to Africa but has become widespread in many tropical and sub-tropical parts of the world.",
        "Square Stalked Vine":" →  Scientifically referred to as Paederia foetida. This site makes an attempt to gather and share common names of the plants found in India. Known for its various therapeutic applications, it's attributed with properties like anti-inflammatory, antimicrobial, and digestive benefits, often used to address conditions such as digestive discomfort, inflammation, and skin ailments. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Stinking Passionflower":" → Scientifically known as Passiflora foetida. Native to South America, stinking passionflower is a climbing vine with an unpleasant smell and flowers that resemble those of the passionfruit vine. Stinking passionflower can invade forest edges, coastal vegetation, roadsides and disturbed areas. It is widespread in northern Queensland. It's attributed with various therapeutic effects, including its application in treating conditions such as insomnia, anxiety, and digestive discomfort. ",
        "Sweet Basil":" →  Scientifically known as Ocimum basilicum. Basil, also called great basil, is a culinary herb of the family Lamiaceae. It is a tender plant, and is used in cuisines worldwide. In Western cuisine, the generic term basil refers to the variety also known as sweet basil or Genovese basil. Basil is native to tropical regions from Central Africa to Southeast Asia. With reported anti-inflammatory, antimicrobial, and antioxidant characteristics, Sweet Basil is believed to aid in digestive health, respiratory issues, and stress relief. Typically safe for diverse age groups and genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. ",
        "Sweet Flag":" → Acorus calamus is a species of flowering plant with psychoactive chemicals. It is a tall wetland monocot of the family Acoraceae, in the genus Acorus. This herb is historically valued for aiding digestion, alleviating gastrointestinal discomfort, and potentially offering anti-inflammatory and cognitive-enhancing properties. While generally considered safe for adults, caution is advised for children due to certain compounds present in the plant. Its use during pregnancy is not recommended due to safety concerns. Dosage and consumption methods can vary, often used sparingly due to its potency.",
        "Tinnevelly Senna":" → Senna alexandrina is an ornamental plant in the genus Senna. It is used in herbalism. It grows natively in upper Egypt, especially in the Nubian region, and near Khartoum, where it is cultivated commercially. It is also grown elsewhere, notably in India and Somalia. Widely used by adults, it's typically cautioned for children and requires medical guidance. This herb doesn't exhibit gender-specific restrictions, but pregnant or breastfeeding women should avoid its use without consulting healthcare professionals due to potential risks.",
        'Trellis Vine':" → Unlike a tree, vines can't support themselves, so a trellis provides this support. Also, trellises keep vines off the ground and therefore minimize disease. They help spread out the canopy for sun exposure, pruning and canopy management. Typically safe for diverse age groups and genders, caution is advisable for pregnant individuals due to the potential risks associated with consuming certain constituents found in grape products during pregnancy. The recommended use of grapes or products derived from the Trellis Vine during pregnancy should be discussed and guided by healthcare professionals.",
        "Velvet Bean":" → Mucuna pruriens is a tropical legume native to Africa and tropical Asia and widely naturalized and cultivated. Its English common names include monkey tamarind, velvet bean, Bengal velvet bean, Florida velvet bean, Mauritius velvet bean, Yokohama velvet bean, cowage, cowitch, lacuna bean, and Lyon bean. It's valued for its potential medicinal properties, primarily attributed to the presence of L-DOPA (levodopa) in its seeds, which is a precursor to dopamine and has been studied for its neurological effects. Traditionally considered safe for various age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Aloevara":" → (Scientific name: Aloe vera) Aloe vera is a succulent plant species of the genus Aloe. It is widely distributed, and is considered an invasive species in many world regions. An evergreen perennial, it originates from the Arabian Peninsula, but grows wild in tropical, semi-tropical, and arid climates around the world. Aloevera is commonly known for its skin-soothing properties and digestive benefits, generally safe for all ages and genders, with caution and healthcare consultation recommended during pregnancy; usage involves applying gel topically for skin conditions and following professional guidance for oral consumption.",
        "Coatbuttons":" → Tridax procumbens, commonly known as coatbuttons or tridax daisy, is a species of flowering plant in the family Asteraceae. It is best known as a widespread weed and pest plant. It is traditionally valued for its anti-inflammatory and antipyretic properties. Generally safe for various age groups and genders, it has been used for skin conditions and respiratory issues. Caution is advised for pregnant individuals. ",
        "Heart Leaved Moonseed":" → Tinospora cordifolia is a herbaceous vine of the family Menispermaceae indigenous to tropical regions of the Indian subcontinent. It has been used in Ayurveda to treat various disorders, but there is no clinical evidence for the effectiveness of such treatment. Its potential medicinal benefits are encompassing immune-boosting and anti-inflammatory properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, necessitating consultation with healthcare professionals. Dosage may vary based on the intended use. Heart-leaved Moonseed can be consumed as teas or extracts, adhering to recommended guidelines for safe and effective utilization.",
        "Nagfani":" → (Scientific name: Meswak or Salvadora persica) Crataegus, commonly called hawthorn, quickthorn, thornapple, May-tree, whitethorn, Mayflower, or hawberry, is a genus of several hundred species of shrubs and trees in the family Rosaceae, native to temperate regions of the Northern Hemisphere in Europe, Asia, North Africa, and North America. And known for its dental hygiene properties and potential medicinal benefits, considered generally safe for oral use, though caution and professional advice are suggested for certain conditions or medications; usage typically involves chewing on twigs for oral hygiene, and specific guidance is advisable for any medicinal application.",
        "Neem":" → Azadirachta indica, commonly known as neem, nimtree or Indian lilac, is a tree in the mahogany family Meliaceae. It is one of two species in the genus Azadirachta, and is native to the Indian subcontinent. It is typically grown in tropical and semi-tropical regions. Neem trees also grow on islands in southern Iran. Its applications span across treating various ailments such as skin disorders, gastrointestinal issues, and infections owing to its antibacterial, antifungal, antiviral, and anti-inflammatory attributes found in its leaves, bark, and seeds. Typically deemed safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects. ", 
        "Tulsi":" → Scientifically known as Ocimum tenuiflorum. Tulsi has also been shown to counter metabolic stress through normalization of blood glucose, blood pressure and lipid levels, and psychological stress through positive effects on memory and cognitive function and through its anxiolytic and anti-depressant properties. It's renowned for its therapeutic benefits, including anti-inflammatory, antioxidant, antimicrobial, and adaptogenic properties. Considered generally safe for various age groups and genders, caution is advised for pregnant individuals due to potential effects on hormone levels and pregnancy. "}
       
        result = result+d[result]
        #result2 = result+d[result]
        #result = [result]
        #result3 = d[result]        
        print(result)
        #print(result3)
        #os.remove(file_path)
        return result
        #return result3
        return None


@app.route('/predict', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        # Get the file from post request
        f = request.files['file']
        file_path = secure_filename(f.filename)
        f.save(file_path)
        # Make prediction
        result = load_image(file_path)
        result = result.title()
        d = {
        "Asthma Plant":" → Euphorbia hirta is a pantropical weed, originating from the tropical regions of the Americas. It is a hairy herb that grows in open grasslands, roadsides and pathways. It is widely used in traditional herbal medicine across many cultures, particularly for asthma, skin ailments, and hypertension. Often recognized for its potential respiratory benefits, considered generally safe for various ages and genders, but pregnant individuals should exercise caution and seek medical advice before use. Its usage typically involves preparing extracts for respiratory support, yet professional guidance is advisable for proper oral consumption or medicinal purposes.",
        'Avaram':" → Senna auriculata is a leguminous tree in the subfamily Caesalpinioideae. It is commonly known by its local names matura tea tree, avaram or ranawara, or the English version avaram senna. It is the State flower of Telangana. It occurs in the dry regions of India and Sri Lanka. Generally safe for all ages and genders, it is traditionally used to address conditions like diabetes and skin disorders. However, caution and consultation with healthcare providers are recommended, especially for young children and during pregnancy. The mode of use typically involves consuming it as a tea or infusion, with proper dosage guided by healthcare professionals. ",
        "Balloon Vine":" → Cardiospermum halicacabum, known as the lesser balloon vine, balloon plant or love in a puff, is a climbing plant widely distributed across tropical and subtropical areas of Africa, Australia, and North America that is often found as a weed along roads and rivers.Generally safe for various age groups and both genders, it has been traditionally used for skin conditions, allergies, and as a mild diuretic. Caution and healthcare consultation are advised, particularly for specific age groups and during pregnancy. Dosage recommendations should be followed under healthcare professional guidance, and the plant's various parts may be used in forms like decoctions or topical applications, adhering to traditional practices and healthcare advice.",
        "Bellyache Bush":" → Jatropha gossypiifolia, commonly known as bellyache bush, black physicnut or cotton-leaf physicnut, is a species of flowering plant in the spurge family, Euphorbiaceae. The species is native to Mexico, Philippines, South America, Gujarat State, and the Caribbean islands. Traditionally used for digestive issues, skin conditions, and as an anti-inflammatory agent, it is generally considered safe for various age groups and genders, with caution and healthcare consultation recommended. Limited research exists on its use during pregnancy, and proper dosage, whether in decoctions, infusions, or topical applications, should be determined under the guidance of healthcare professionals and traditional practices.",
        "Benghal Dayflower":" → Commelina benghalensis, commonly known as the Benghal dayflower, tropical spiderwort, or wandering Jew, kanshira in Bengali, is a perennial herb native to tropical Asia and Africa. Traditionally used for its diuretic properties and in the treatment of inflammatory conditions, it is generally considered safe for various age groups and both genders, with caution and healthcare consultation recommended. Limited research exists on its use during pregnancy, and proper dosage, whether in infusions or topical applications, should be determined under the guidance of healthcare professionals and traditional practices.",
        "Big Caltrops":" → A caltrop also known as caltrap, galtrop, cheval trap, galthrap, galtrap, calthrop, jackrock or crow's foot is an area denial weapon made up of two or more sharp nails or spines arranged in such a manner that one of them always points upward from a stable base for example, a tetrahedron. Historically, caltrops were part of defences that served to slow the advance of troops, especially horses, chariots, and war elephants, and were particularly effective against the soft feet of camels. In modern times, caltrops are effective when used against wheeled vehicles with pneumatic tires. Typically, it's consumed as a supplement, yet guidance from experts is recommended for appropriate dosages and usage.",
        "Black Honey Shrub":" → (Phyllanthus reticulatus) Black-Honey Shrub is usually a much-branched somewhat climbing shrub, rarely a small tree. Leaves are ovate-oblong to elliptic, 1-5 cm long, 0.7-3 cm wide, produced on short lateral branchlets, looking like leaflets of a compound leaf. The plant has medicinal uses, treating conditions like malaria and diabetes. It also has practical applications; stems are used for hut construction, twigs as toothbrushes, and fruits, roots, and stems yield black ink and dye. Ripe fruits are consumed during famine and sold in markets. Propagation is done through seeds. The Black-honey shrub serves diverse purposes in traditional medicine, daily life, and local economies.",
        "Bristly Wild Grape":" → Cyphostemma setosum - Bristly Wild Grape is a succulent climber clothed with bristly hairs. Leaves are trifoliate rarely lower ones simple, fleshy, nearly stalkless, shortly stalked, elliptic, ovoate to obovate, blunt, rounded at the base, stringly sawtoothed, up to 7 x 5 cms. Often acknowledged for its potential benefits related to joint health and bone support, considered generally safe for various ages and genders. However, pregnant individuals should approach its usage with caution and seek medical advice before use. It's typically utilized by preparing extracts for joint-related issues, yet professional guidance is recommended for oral consumption or medicinal purposes. ",
        "Butterfly Pea":" → Clitoria ternatea, commonly known as Asian pigeonwings, bluebellvine, blue pea, butterfly pea, cordofan pea or Darwin pea is a plant species belonging to the family Fabaceae, endemic and native to the Indonesian island of Ternate. In India, it is revered as a holy flower, used in daily puja rituals. Pregnant individuals should exercise caution and seek advice from healthcare professionals regarding its use. Understanding recommended daily doses and modes of consumption is paramount, with guidance from healthcare practitioners or herbalists ensuring safe and effective utilization.",
        'Cape Gooseberry':" → Physalis peruviana, is a South American plant native to Colombia, Ecuador and Peru in the nightshade family, commonly known as Cape gooseberry or goldenberry. Rich in vitamins and antioxidants, it contributes to overall health, although it's not specifically associated with curing diseases. Generally safe for all ages, its consumption is versatile and can be enjoyed fresh, in salads, desserts, or jams. There are no strict daily doses, but moderation is recommended. Cape Gooseberry is commonly consumed by both men and women, and while it is generally considered safe during pregnancy, individual reactions may vary, necessitating consultation with healthcare professionals for personalized advice.",
        "Common Wireweed":" → Sida acuta, the common wireweed, is a species of flowering plant in the mallow family, Malvaceae. It is believed to have originated in Central America, but today has a pantropical distribution and is considered a weed in some areas. It is recognized in traditional medicine for its potential diuretic and anti-inflammatory properties. Generally safe for various age groups and both genders, caution is advised for pregnant individuals. Common Wireweed can be used in different forms, such as teas or infusions, with adherence to recommended guidelines ensuring safe and effective utilization.",
        "Country Mallow":" → Sida cordifolia is a perennial subshrub of the mallow family Malvaceae native to India. It has naturalized throughout the world, and is considered an invasive weed in Africa, Australia, the southern United States, Hawaiian Islands, New Guinea, and French Polynesia. Is esteemed for its traditional medicinal uses, encompassing anti-inflammatory and anti-asthmatic properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals.",
        "Crown Flower":" → Calotropis gigantea, the crown flower, is a species of Calotropis native to Cambodia, Vietnam, Bangladesh, Indonesia, Malaysia, Thailand, Sri Lanka, India, China, Pakistan, and Nepal. It is a large shrub growing to 4 m tall. It has clusters of waxy flowers that are either white or lavender in colour. Traditional medicinal uses is boasting anti-inflammatory and anti-fungal properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage depends on the intended use, with guidance from healthcare practitioners. ",
        "Green Chireta":" → Andrographis paniculata, commonly known as creat or green chiretta, is an annual herbaceous plant in the family Acanthaceae, native to India and Sri Lanka. It is widely cultivated in Southern and Southeastern Asia, where it has been believed to be a treatment for bacterial infections and some diseases. Particularly used for immune-boosting and anti-inflammatory properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, necessitating consultation with healthcare professionals. Dosage depends on the intended use.",
        "Holy Basil":" → Ocimum tenuiflorum, commonly known as holy basil, tulsi or tulasi, is an aromatic perennial plant in the family Lamiaceae. It is native to the Indian subcontinent and widespread as a cultivated plant throughout the Southeast Asian tropics. Its potential medicinal properties, includes anti-inflammatory and antioxidant effects. It's used traditionally for respiratory conditions, stress, and digestive issues. Generally considered safe for all ages. It is generally used by both men and women. Dosage may vary based on the form of use (tea, supplement, etc.).Holy Basil can be consumed as tea, in culinary dishes, or taken as supplements. It's also used topically.",
        "Indian Copperleaf":" → Acalypha indica is an herbaceous annual that has catkin-like inflorescences with cup-shaped involucres surrounding the minute flowers. It is mainly known for its root being attractive to domestic cats, and for its various medicinal uses. It occurs throughout the Tropics. Traditional medicinal applications are anti-inflammatory and antifungal properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage may vary depending on the intended use, and guidance from healthcare practitioners.",
        "Indian Jujube":" → Ziziphus mauritiana, also known as Indian jujube, Indian plum, Chinese date, Chinese apple, ber, and dunks is a tropical fruit tree species belonging to the family Rhamnaceae. It is prized for its nutritional richness and potential health benefits. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage may vary based on the intended use, and guidance from healthcare practitioners. Indian Jujube is a versatile ingredient in various culinary dishes, with adherence to recommended guidelines ensuring safe and effective utilization.  ",
	    'Indian Sarsaparilla':" → Hemidesmus indicus, Indian sarsaparilla is a species of plant found in South Asia. It occurs over the greater part of India, from the upper Gangetic plain eastwards to Assam and in some places in central, western and South India. The root is a substitute for sarsaparilla. Is esteemed for its traditional medicinal uses, encompassing anti-inflammatory and antioxidant properties. Generally safe for various age groups and both genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage may vary based on the intended use, with guidance from healthcare practitioners or herbalists recommended. Often consumed as a herbal decoction.",
        "Indian Stinging Nettle":" → Tragia involucrata, the Indian stinging nettle, is a species of plant in the family Euphorbiaceae. It's known for treating conditions like arthritis, allergies, and skin ailments due to its anti-inflammatory and antihistaminic properties. This plant, while widely considered safe for most ages and genders, requires caution during pregnancy due to limited research on its effects. Consulting healthcare professionals is advisable before usage, especially for pregnant women or individuals with specific health concerns. Doses for daily use may vary, often consumed as teas, extracts, or in topical forms for skin conditions.",
        "Indian Thornapple":" → Datura innoxia, known as pricklyburr, recurved thorn-apple, downy thorn-apple, Indian-apple, lovache, moonflower, nacazcul, toloatzin, toloaxihuitl, tolguache or toloache, is a species of flowering plant in the family Solanaceae. is a flowering plant native to India and Southeast Asia. Recognized for its trumpet-shaped flowers and spiky fruits, it contains toxic tropane alkaloids. While historically used in traditional medicine for its potential psychoactive properties, its toxicity makes it risky and not recommended for such purposes. There are no safe age groups, and use is generally discouraged for all individuals. The toxic effects apply universally, regardless of gender. No safe dosage exists, emphasizing the plant's inherent risks. ",
        "Indian Wormwood":" → Scientifically known as Artemisia Indica. Indian Wormwood is found in India and East Asia. It is found in the Himalayas at altitudes of 300-2400 m. Flowering: August-October. Medicinal uses: An infusion of leaves is used in the treatment of nervous and spasmodic affections, in asthma and in diseases of the brain. Recognized for its aromatic, silvery-green leaves, it has been traditionally used in medicine for its potential anti-inflammatory and antimicrobial properties. Caution is advised, as some Artemisia species, including A.absinthium, may have toxic components. Generally considered safe, caution is advised for pregnant individuals, and consulting healthcare professionals is recommended for specific use during pregnancy. Dosage may vary based on the intended application, and guidance from herbalists or healthcare practitioners is advisable.",
        "Ivy Gourd":" → Scientifically known as Coccinia grandis. Ivy gourd is a plant. The leaves, root, and fruit are used to make medicine. Ivy gourd is most often used for diabetes. People also use ivy gourd for gonorrhea, constipation, wounds, and other conditions, but there is no good scientific evidence to support these uses. Recognized for its small, cucumber-like fruits, it is a popular ingredient in Asian cuisine, featured in dishes like stir-fries and curries. Besides its culinary uses, ivy gourd is known for potential health benefits, including traditional medicinal applications such as managing diabetes.Generally safe for consumption across age groups and genders, pregnant individuals should consult healthcare professionals for personalized advice.",
        "Kokilaksha":" → Scientifically known as Asteracantha longifolia. The plant is an Ayurvedic herb used to make medicines for several gastrointestinal, kidney, reproductive, liver, and bone disorders. Kokilaksha is native to India and also to other places like Srilanka, Malaysia, Nepal and Myanmar. Kokilaksha means having eyes like Kokila the Indian cuckoo. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. Dosages for daily use may vary based on the intended purpose and formulation, often administered as decoctions, powders, or in traditional formulations. No specific age or gender restrictions are typically outlined due to its traditional usage.",
        "Land Caltrops":" → Tribulus terrestris is an annual plant in the caltrop family widely distributed around the world. It is adapted to thrive in dry climate locations in which few other plants can survive. It is native to warm temperate and tropical regions in southern Eurasia and Africa. Recognized for its spiky fruits, it has traditional uses in herbal medicine, particularly for male reproductive health. Additionally, it's popular in fitness communities as a supplement.  Caution is advised, and consulting with a healthcare professional is recommended before using it for medicinal or supplemental purposes. Generally considered safe for various age groups, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. ",
        "Madagascar Periwinkle":" → Catharanthus roseus, commonly known as bright eyes, Cape periwinkle, graveyard plant, Madagascar periwinkle, old maid, pink periwinkle, rose periwinkle, is a species of flowering plant in the family Apocynaceae. It is native and endemic to Madagascar, but grown elsewhere as an ornamental and medicinal plant. This vibrant and low-maintenance flowering plant is recognized for its attractive blooms and medicinal properties. The plant produces glossy, dark green leaves and flowers with shades of pink, red, or white. Madagascar periwinkle contains alkaloids that have been used in traditional medicine, and it's a source of compounds used in the production of certain chemotherapy drugs for treating cancer. Despite its beauty, the plant is toxic and should be handled with care.",
        'Madras Pea Pumpkin':" → Scientifically known as Cucumis maderaspatanus. Madras pea pumpkin is a perennial herb, climbing or trailing up to 3 m, stem bristly-hairy. Tendrils are simple, thread-like. Leaves are arrow shaped, hastate, ...  Often associated with managing blood sugar levels and aiding digestion. Considered generally safe for various age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. As for age restrictions, it's suitable for consumption across different age brackets when used as a food source. However, specific medicinal doses and usage might require guidance, especially for pregnant women or individuals with health conditions.",
        "Malabar Catmint":" → Anisomeles indica, or catmint, is a species of herbaceous plant native to eastern Asia and naturalized on some Pacific islands. The plant is valued for its potential medicinal properties, including anti-inflammatory and antibacterial effects. It thrives in warm climates, is low-maintenance, and can be grown in pots or in well-drained soil.",
        "Mexican Mint":" → Coleus amboinicus, synonym Plectranthus amboinicus, is a semi-succulent perennial plant in the family Lamiaceae with a pungent oregano-like flavor and odor. Its ability to improve the health of your skin, detoxify the body, defend against colds, ease the pain of arthritis, relieve stress and anxiety, treat certain kinds of cancer, and optimize digestion. Generally considered safe for various age groups, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. Dosage varies based on the intended use.",
        "Mexican Prickly Poppy":" → Argemone mexicana is a species of poppy found in Mexico and now widely naturalized in many parts of the world. An extremely hardy pioneer plant, it is tolerant of drought and poor soil, often being the only cover on new road cuttings or verges. It has bright yellow latex. It has a history of traditional medicinal uses, including addressing skin conditions, respiratory issues, and serving as a mild sedative. However, caution is essential as the plant contains alkaloids that can be toxic, particularly in its seeds. Medicinal use, especially internal consumption, should be approached with care, and consultation with healthcare professionals is advised.",
        "Mountain Knotgrass":" → Aerva lanata, the mountain knotgrass, is a woody, prostrate or succulent, perennial herb in the family Amaranthaceae, native to Asia, Africa. It has been included as occurring in Australia by the US government, but it is not recognised as occurring in Australia by any Australian state herbarium. Various parts of the plant have been employed in treating conditions such as kidney stones, urinary disorders, and as a diuretic in traditional medicine. With potential anti-inflammatory and antimicrobial properties, caution is advised, and consultation with healthcare professionals is recommended, especially for pregnant individuals.",
        "Nalta Jute":" → Scientifically known as Corchorus olitorius. Jute mallow or nalta jute is a species of shrub in the family Malvaceae. Together with C. capsularis it is the primary source of jute fiber. The leaves and young fruits are used as a vegetable, the dried leaves are used for tea and as a soup thickener, and the seeds are edible.  While not primarily recognized for extensive medicinal applications, some traditional practices attribute mild therapeutic benefits. It is commonly used in various culinary dishes, contributing a unique flavor profile. Generally considered safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy.",
        "Night Blooming Cereus":" → Scientifically as Selenicereus grandiflorus. Regardless of genus or species, night-blooming cereus flowers are almost always white or very pale shades of other colors, often large, and frequently fragrant. Most of the flowers open after nightfall, and by dawn, most are in the process of wilting. Benefits such as aiding in insomnia and relieving certain mild digestive discomforts, though scientific evidence supporting these claims remains limited. Typically considered safe for diverse age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy.",
        "Panicled Foldwing":" → Dicliptera paniculata - Panicled Foldwing. Panicled Foldwing is an erect herb, 0.6-1.2 m tall. Young shoots are usually 4-sided; adult shoots 6-sided, white spreading bristle-hairy. Ovate leaves opposite, equal and unequal; leaf-stalk 3-5 mm. Benefits such as aiding in digestive discomfort or minor skin conditions, although scientific evidence supporting these claims is limited or anecdotal. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to the lack of comprehensive research on its effects during pregnancy.",
        "Prickly Chaff Flower":" → Achyranthes aspera is a species of plant in the family Amaranthaceae. It is distributed throughout the tropical world. It can be found in many places growing as an introduced species and a common weed. It is an invasive species in some areas, including many Pacific Islands environments. It's attributed with properties such as anti-inflammatory, antimicrobial, and antipyretic (fever-reducing) characteristics, often used to address conditions like wounds, skin ailments, fever, and digestive discomfort. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Punarnava":" → Boerhaavia diffusa is a species of flowering plant in the four o'clock family which is commonly known as punarnava, red spiderling, spreading hogweed, or tarvine. It is taken in herbal medicine for pain relief and other uses. The leaves of Boerhaavia diffusa are often used as a green vegetable in many parts of India. Renowned for its diuretic properties, it's often used to support kidney and urinary health. Additionally, Punarnava is attributed with anti-inflammatory, hepatoprotective (liver-protective), and antioxidant characteristics. Generally regarded as safe for various age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy.",
        'Purple Fruited Pea Eggplant':" → Scientifically as Solanum trilobatum. It is a very good brain stimulant. It removes chest, nose and head congestion. It relieves dyspepsia impairment of digestion. In traditional medicine, it's commonly used to address respiratory issues like coughs, colds, and asthma, as well as for skin conditions and digestive discomfort. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Purple Tephrosia":" → Tephrosia purpurea is a species of flowering plant in the family Fabaceae, that has a pantropical distribution. It is a common wasteland weed. In many parts it is under cultivation as green manure crop. It is found throughout India and Sri Lanka in poor soils. Common names include: Bengali. It's attributed with various therapeutic effects, including anti-inflammatory, antioxidant, and antimicrobial properties. In traditional practices, it's often used to address conditions such as digestive issues, skin ailments, and inflammatory conditions. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Rosary Pea":" → Abrus precatorius, commonly known as jequirity bean or rosary pea, is a herbaceous flowering plant in the bean family Fabaceae. It is a slender, perennial climber with long, pinnate-leafleted leaves that twines around trees, shrubs, and hedges.  While its seeds are visually appealing, they contain a toxic compound called abrin, making them highly poisonous if ingested. Due to this toxicity, it's crucial to handle the seeds with extreme caution and prevent accidental ingestion, as even a small amount can be lethal. Despite its toxic nature, the plant has been historically used in some traditional practices for its purported medicinal properties, including potential applications in treating various ailments. ",
        "Shaggy Button Weed":" → Scientifically known as Diodia virginiana, is a small flowering plant found in various regions. While not prominently recognized for medicinal use, some traditional practices attribute mild potential benefits, often citing its usage for minor ailments or as a mild diuretic. Typically considered safe for diverse age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Small Water Clover":" → Scientifically known as Marsilea minuta. Water clovers are fast growers, with vestita and quadrifolia ranging between 4 inches and one foot of maximum height, depending on water depth ... Often using it for minor ailments or as part of traditional remedies. Generally considered safe for diverse age groups and genders, caution is advisable for pregnant individuals due to limited research on its effects during pregnancy.",
        "Spiderwisp":" → It is known by many common names including Shona cabbage, African cabbage, spiderwisp, cat's whiskers, chinsaga and stinkweed. It is an annual wildflower native to Africa but has become widespread in many tropical and sub-tropical parts of the world.",
        "Square Stalked Vine":" →  Scientifically referred to as Paederia foetida. This site makes an attempt to gather and share common names of the plants found in India. Known for its various therapeutic applications, it's attributed with properties like anti-inflammatory, antimicrobial, and digestive benefits, often used to address conditions such as digestive discomfort, inflammation, and skin ailments. Considered generally safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Stinking Passionflower":" → Scientifically known as Passiflora foetida. Native to South America, stinking passionflower is a climbing vine with an unpleasant smell and flowers that resemble those of the passionfruit vine. Stinking passionflower can invade forest edges, coastal vegetation, roadsides and disturbed areas. It is widespread in northern Queensland. It's attributed with various therapeutic effects, including its application in treating conditions such as insomnia, anxiety, and digestive discomfort. ",
        "Sweet Basil":" →  Scientifically known as Ocimum basilicum. Basil, also called great basil, is a culinary herb of the family Lamiaceae. It is a tender plant, and is used in cuisines worldwide. In Western cuisine, the generic term basil refers to the variety also known as sweet basil or Genovese basil. Basil is native to tropical regions from Central Africa to Southeast Asia. With reported anti-inflammatory, antimicrobial, and antioxidant characteristics, Sweet Basil is believed to aid in digestive health, respiratory issues, and stress relief. Typically safe for diverse age groups and genders, caution is advised for pregnant individuals, warranting consultation with healthcare professionals. ",
        "Sweet Flag":" → Acorus calamus is a species of flowering plant with psychoactive chemicals. It is a tall wetland monocot of the family Acoraceae, in the genus Acorus. This herb is historically valued for aiding digestion, alleviating gastrointestinal discomfort, and potentially offering anti-inflammatory and cognitive-enhancing properties. While generally considered safe for adults, caution is advised for children due to certain compounds present in the plant. Its use during pregnancy is not recommended due to safety concerns. Dosage and consumption methods can vary, often used sparingly due to its potency.",
        "Tinnevelly Senna":" → Senna alexandrina is an ornamental plant in the genus Senna. It is used in herbalism. It grows natively in upper Egypt, especially in the Nubian region, and near Khartoum, where it is cultivated commercially. It is also grown elsewhere, notably in India and Somalia. Widely used by adults, it's typically cautioned for children and requires medical guidance. This herb doesn't exhibit gender-specific restrictions, but pregnant or breastfeeding women should avoid its use without consulting healthcare professionals due to potential risks.",
        'Trellis Vine':" → Unlike a tree, vines can't support themselves, so a trellis provides this support. Also, trellises keep vines off the ground and therefore minimize disease. They help spread out the canopy for sun exposure, pruning and canopy management. Typically safe for diverse age groups and genders, caution is advisable for pregnant individuals due to the potential risks associated with consuming certain constituents found in grape products during pregnancy. The recommended use of grapes or products derived from the Trellis Vine during pregnancy should be discussed and guided by healthcare professionals.",
        "Velvet Bean":" → Mucuna pruriens is a tropical legume native to Africa and tropical Asia and widely naturalized and cultivated. Its English common names include monkey tamarind, velvet bean, Bengal velvet bean, Florida velvet bean, Mauritius velvet bean, Yokohama velvet bean, cowage, cowitch, lacuna bean, and Lyon bean. It's valued for its potential medicinal properties, primarily attributed to the presence of L-DOPA (levodopa) in its seeds, which is a precursor to dopamine and has been studied for its neurological effects. Traditionally considered safe for various age groups and genders, caution is advised for pregnant individuals due to limited research on its effects during pregnancy. ",
        "Aloevara":" → (Scientific name: Aloe vera) Aloe vera is a succulent plant species of the genus Aloe. It is widely distributed, and is considered an invasive species in many world regions. An evergreen perennial, it originates from the Arabian Peninsula, but grows wild in tropical, semi-tropical, and arid climates around the world. Aloevera is commonly known for its skin-soothing properties and digestive benefits, generally safe for all ages and genders, with caution and healthcare consultation recommended during pregnancy; usage involves applying gel topically for skin conditions and following professional guidance for oral consumption.",
        "Coatbuttons":" → Tridax procumbens, commonly known as coatbuttons or tridax daisy, is a species of flowering plant in the family Asteraceae. It is best known as a widespread weed and pest plant. It is traditionally valued for its anti-inflammatory and antipyretic properties. Generally safe for various age groups and genders, it has been used for skin conditions and respiratory issues. Caution is advised for pregnant individuals. ",
        "Heart Leaved Moonseed":" → Tinospora cordifolia is a herbaceous vine of the family Menispermaceae indigenous to tropical regions of the Indian subcontinent. It has been used in Ayurveda to treat various disorders, but there is no clinical evidence for the effectiveness of such treatment. Its potential medicinal benefits are encompassing immune-boosting and anti-inflammatory properties. Generally safe for diverse age groups and both genders, caution is advised for pregnant individuals, necessitating consultation with healthcare professionals. Dosage may vary based on the intended use. Heart-leaved Moonseed can be consumed as teas or extracts, adhering to recommended guidelines for safe and effective utilization.",
        "Nagfani":" → (Scientific name: Meswak or Salvadora persica) Crataegus, commonly called hawthorn, quickthorn, thornapple, May-tree, whitethorn, Mayflower, or hawberry, is a genus of several hundred species of shrubs and trees in the family Rosaceae, native to temperate regions of the Northern Hemisphere in Europe, Asia, North Africa, and North America. And known for its dental hygiene properties and potential medicinal benefits, considered generally safe for oral use, though caution and professional advice are suggested for certain conditions or medications; usage typically involves chewing on twigs for oral hygiene, and specific guidance is advisable for any medicinal application.",
        "Neem":" → Azadirachta indica, commonly known as neem, nimtree or Indian lilac, is a tree in the mahogany family Meliaceae. It is one of two species in the genus Azadirachta, and is native to the Indian subcontinent. It is typically grown in tropical and semi-tropical regions. Neem trees also grow on islands in southern Iran. Its applications span across treating various ailments such as skin disorders, gastrointestinal issues, and infections owing to its antibacterial, antifungal, antiviral, and anti-inflammatory attributes found in its leaves, bark, and seeds. Typically deemed safe for diverse age groups and genders, caution is advised for pregnant individuals due to limited research on its effects. ", 
        "Tulsi":" → Scientifically known as Ocimum tenuiflorum. Tulsi has also been shown to counter metabolic stress through normalization of blood glucose, blood pressure and lipid levels, and psychological stress through positive effects on memory and cognitive function and through its anxiolytic and anti-depressant properties. It's renowned for its therapeutic benefits, including anti-inflammatory, antioxidant, antimicrobial, and adaptogenic properties. Considered generally safe for various age groups and genders, caution is advised for pregnant individuals due to potential effects on hormone levels and pregnancy. "}
       
        result = result+d[result]
        #result2 = result+d[result]
        #result = [result]
        #result3 = d[result]        
        print(result)
        #print(result3)
        os.remove(file_path)
        return result
        #return result3
    return None

if __name__ == '__main__':
    app.run(debug = True)